export const users = [
  {
    id: "1",
    name: "John Doe",
    email: "johndoe@example.com",
    username: "johndoe",
    role: "user",
    status: "active",
    imageUrl: "https://example.com/johndoe.jpg",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "janesmith@example.com",
    username: "janesmith",
    role: "admin",
    status: "active",
    imageUrl: "https://example.com/janesmith.jpg",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mikejohnson@example.com",
    username: "mikejohnson",
    role: "user",
    status: "inactive",
    imageUrl: "https://example.com/mikejohnson.jpg",
  },
  {
    id: "4",
    name: "Sarah Williams",
    email: "sarahwilliams@example.com",
    username: "sarahwilliams",
    role: "user",
    status: "active",
    imageUrl: "https://example.com/sarahwilliams.jpg",
  },
  {
    id: "5",
    name: "David Brown",
    email: "davidbrown@example.com",
    username: "davidbrown",
    role: "accountant",
    status: "active",
    imageUrl: "https://example.com/davidbrown.jpg",
  },
  {
    id: "6",
    name: "Emily Davis",
    email: "emilydavis@example.com",
    username: "emilydavis",
    role: "user",
    status: "inactive",
    imageUrl: "https://example.com/emilydavis.jpg",
  },
  {
    id: "7",
    name: "Michael Wilson",
    email: "michaelwilson@example.com",
    username: "michaelwilson",
    role: "user",
    status: "active",
    imageUrl: "https://example.com/michaelwilson.jpg",
  },
  {
    id: "8",
    name: "Jessica Taylor",
    email: "jessicataylor@example.com",
    username: "jessicataylor",
    role: "admin",
    status: "active",
    imageUrl: "https://example.com/jessicataylor.jpg",
  },
  {
    id: "9",
    name: "Matthew Anderson",
    email: "matthewanderson@example.com",
    username: "matthewanderson",
    role: "user",
    status: "inactive",
    imageUrl: "https://example.com/matthewanderson.jpg",
  },
  {
    id: "10",
    name: "Olivia Martinez",
    email: "oliviamartinez@example.com",
    username: "oliviamartinez",
    role: "user",
    status: "active",
    imageUrl: "https://example.com/oliviamartinez.jpg",
  },
];
