import "./globals.css";

import Footer from "./_components/footer/Footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import NavBar from "./_components/navbar/NavBar";
import Sidebar from "./_components/sidebar/Sidebar";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PICO ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`max-w-screen ${inter.className}`}>
        <StoreProvider>
          <div className="flex flex-col min-h-screen">
            <NavBar />
            <div className="flex flex-grow">
              <Sidebar />
              <main className="flex flex-col w-full">
                <div className="mx-5 flex-grow rounded-md">{children}</div>
                <Footer />
              </main>
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
